### PR TITLE
Parse files always with erb

### PR DESCRIPTION
**Pull request by jakolehm**
`.erb` files are not very convenient with most of code editors. If we parse `.yaml` files through erb it should catch most common templating errors faster.

### CODE REVIEW

**Comment by kke** [comment]
Security-wise it's not kosher to run code from files that are not supposed to contain code. But Mortar doesn't use `safe_load` either, so there's a chance it could execute some code from regular YAMLs too. (Kyaml includes a `YAML#safe_load_stream` extension to avoid that). That is the reason why the feature to separate `.yml` and `.yml.erb` was added in the first place.

Most editors can be configured to treat `.yml.erb` as YAML. In VS Code you can do something like:

```json
{
"files.associations": {"*.yml.erb": "yaml"}
 }
```

And in Atom:

```json
"file-types": [
    {
      ".yml.erb$": "source.yaml"
    }
]
```

Vim already uses `eruby` ftype to edit `.yml.erb` and it seems to understand YAML indentations and highlighting just fine and handles the erb part too.

**Comment by jakolehm** [comment]
> Security-wise it's not kosher to run code from files that are not supposed to contain code.

But we do it anyway if a file is ending with `.erb`. Not sure if this makes it any worse than it already is? /cc @jnummelin

**Comment by kke** [comment]
Well, it's kind of like extracting a `.zip` and surprisingly some code runs. Of course the files are mostly made by yourself I suppose so you should know what's in them.

**Comment by jnummelin** [comment]
I don't see this as a problem, until we start to support something like `mortar fire https://github.com/foo/bar/manifests my-fancy-app`. Then it's another story. But we're not there yet, and IMHO it's always very very slippery slope to shoot random manifests from internetz. With or without erbing them.

**Comment by jakolehm** [comment]
IMO remote manifests does not make this any worse either. Anyway user needs to understand what manifests contain.. does it really make big difference if all files can have erb snippets? Separate `.erb` is only handy if user looks only filenames and not the actual contents.

**Comment by jakolehm** [comment]
@jnummelin 0.2.0 milestone prhps?

**Pull request merged**
