### PR TITLE
Update to k8s-client 0.9 and use K8s::Client.autoconfig for client configuration

### LINKED ISSUE #93: binary install: Tried to load unspecified class: Time (Psych::DisallowedClass)
with https://github.com/kontena/mortar/releases/download/v0.3.2/mortar-darwin-amd64-0.3.2

```
$ mortar fire --var name=aa webdriver.yaml aa
/__enclose_io_memfs__/lib/ruby/2.4.0/psych/class_loader.rb:97:in `find': Tried to load unspecified class: Time (Psych::DisallowedClass)
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/class_loader.rb:28:in `load'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/scalar_scanner.rb:124:in `parse_time'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/scalar_scanner.rb:63:in `tokenize'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:60:in `deserialize'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:330:in `block in register_empty'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:330:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:330:in `register_empty'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Sequence'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/psych.rb:302:in `safe_load'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/k8s-client-0.8.1/lib/k8s/config.rb:106:in `load_file'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/kontena-mortar-0.3.2/lib/mortar/mixins/client_helper.rb:14:in `create_client'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/kontena-mortar-0.3.2/lib/mortar/mixins/client_helper.rb:7:in `client'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/kontena-mortar-0.3.2/lib/mortar/fire_command.rb:64:in `execute'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.3.0/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/kontena-mortar-0.3.2/bin/mortar:13:in `<top (required)>'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/mortar:23:in `load'
	from /__enclose_io_memfs__/lib/ruby/gems/2.4.0/bin/mortar:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #93

The `K8s::Client.autoconfig` was mostly copied from mortar.

### CODE REVIEW

**Comment by jnummelin** [comment]
Seems to cause some spec failures

**Comment by kke** [comment]
Yes, and they're because of https://github.com/kontena/k8s-client/pull/107

**Comment by jakolehm** [comment]
> Yes, and they're because of [kontena/k8s-client#107](https://github.com/kontena/k8s-client/pull/107)

Latest k8s-client includes this PR.

**Comment by kke** [comment]
Bumped k8s-client to 0.9 and specs seem to pass now.

**Comment by kke** [comment]
Also closed by #102

**Pull request closed without merging**
